package pl.kozyra.tau.DAO;

import pl.kozyra.tau.Domain.RPGfigure;

import java.sql.*;
import java.util.*;

public class FigureDao implements DAO<RPGfigure> {

    private Connection connection;

    private PreparedStatement addFigureStmt;
    private PreparedStatement getAllFiguresStmt;
    private PreparedStatement deleteFigureStmt;
    private PreparedStatement getFigureStmt;
    private PreparedStatement updateFigureStmt;


    public FigureDao(Connection connection) throws SQLException {
        this.connection = connection;

        setConnection(connection);
    }

    public FigureDao(){

    }

    public void createTables() throws SQLException {
        connection.createStatement()
                .executeUpdate("CREATE TABLE" +
                        "RPGfigure(id bigint GENERATED BY DEFAULT AS IDENTITY, " +
                        "name varchar (30) NOT NULL, " + "hp integer )");
    }

    private boolean isDatabaseReady() {
        try {
            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("RPGfigure".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }
            return tableExists;
        } catch (SQLException e) {
            return false;
        }
    }

    @Override
    public Connection getConnection() {
        return connection;
    }

    @Override
    public void setConnection(Connection connection) throws SQLException {
        this.connection = connection;
        addFigureStmt = connection.prepareStatement(
                "INSERT INTO RPGfigure (name, hp) VALUES (?, ?)",
                Statement.RETURN_GENERATED_KEYS);
        deleteFigureStmt = connection.prepareStatement("DELETE FROM RPGfigure where id = ?");
        getAllFiguresStmt = connection.prepareStatement("SELECT id, name, hp FROM RPGfigure ORDER BY id");
        getFigureStmt = connection.prepareStatement("SELECT id, name, hp FROM EPGfigure WHERE id = ?");
        updateFigureStmt = connection.prepareStatement("UPDATE RPGfigure SET name=?,hp=? WHERE id = ?");
    }

    @Override
    public List<RPGfigure> getAllFigures() {
        return null;
    }

    @Override
    public int addFigure(RPGfigure figure) {
        return 0;
    }

    @Override
    public int deleteFigure(RPGfigure figure) {
        return 0;
    }

    @Override
    public int updateFigure(RPGfigure figure) throws SQLException {
        return 0;
    }

    @Override
    public RPGfigure getFigure(long id) throws SQLException {
        return null;
    }
}
